spring.application.name=api-gateway
server.port=9000

# Actuator Endpoints
management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Eureka Discovery Endpoints
product.service.url=lb://SERVICE-PRODUCT
