# Configuración común para todos los microservicios
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

# Configuración de Eureka (Discovery Client)
eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}

# Actuator: Exponer endpoints críticos para todos
management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh,bus-refresh,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

# Configuración de Resiliencia (Valores por defecto)
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
