global:
  message: Estás en el entorno DEFAULT
spring:
  application:
    name: service-order
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: f5antos
    password: 123456
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1 # capa más externa
    instances:
      productosCB:
        slidingWindowSize: 6          # Mira las últimas 6 llamadas
        failureRateThreshold: 50      # Si 3 de 6 fallan, abre el circuito
        waitDurationInOpenState: 20s  # Tiempo que se queda el "fusible" fuera
        permittedNumberOfCallsInHalfOpenState: 2
        

  retry:
    retry-aspect-order: 2         # Capa más interna (envuelve al fallback Method)
    instances:
      productosRetry:
        maxAttempts: 3                # Reintenta hasta 3 veces
        waitDuration: 2s              # Espera 2s entre reintentos
        retryExceptions:
          - java.io.IOException
          - org.springframework.web.client.HttpStatusCodeException # Captura 4xx y 5xx
          - java.util.concurrent.CompletionException # Importante para CompletableFuture
          - java.util.concurrent.TimeoutException # Importante para TimeLimiter
          
  threadpoolbulkhead:
    thread-pool-bulkhead-aspect-order: 3
    instances:
      productosBH:
        maxThreadPoolSize: 2      # Solo 2 hilos trabajando a la vez para este cliente
        coreThreadPoolSize: 1     # 1 hilo siempre listo
        queueCapacity: 1
          
  timelimiter:
    time-limiter-aspect-order: 4
    instances:
      productosTL:
        timeoutDuration: 2s           # Si tarda más de 2s, corta la conexión
        cancelRunningFuture: true     # Las tareas bloqueadas no continúan ejecutándose en segundo plano
