global:
  message: Estás en el entorno DEFAULT
spring:
  application:
    name: service-order
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: f5antos
    password: 123456
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

resilience4j:
  circuitbreaker: # Patrón
    instances:
      productosCB: # Nombre que le daremos al circuito (backendA, backendB...)
        registerHealthIndicator: true # para Actuator
        slidingWindowSize: 10          # Mira las últimas 10 llamadas
        failureRateThreshold: 50       # Si falla el 50%, abre el circuito
        waitDurationInOpenState: 10s   # Espera 10s antes de intentar reconectar
        permittedNumberOfCallsInHalfOpenState: 3  # Llamadas de prueba en Semi-Abierto
