global:
  message: Estás en el entorno DEFAULT
spring:
  application:
    name: service-order
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: f5antos
    password: 123456
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8083

resilience4j:
  circuitbreaker:
    instances:
      productosCB:
        slidingWindowSize: 10          # Mira las últimas 10 llamadas
        failureRateThreshold: 50      # Si 3 de 6 fallan, abre el circuito
        waitDurationInOpenState: 20s  # Tiempo que se queda el "fusible" fuera
        permittedNumberOfCallsInHalfOpenState: 2

  retry:
    instances:
      productosRetry:
        maxAttempts: 3                # Reintenta hasta 3 veces
        waitDuration: 2s              # Espera 1s entre reintentos
        retryExceptions:
          - java.io.IOException
          - org.springframework.web.client.HttpStatusCodeException # Captura 4xx y 5xx
          - java.util.concurrent.CompletionException # Importante para CompletableFuture

  timelimiter:
    instances:
      productosTL:
        timeoutDuration: 2s           # Si tarda más de 2s, corta la conexión
